spring.application.name=springboot_mvc_proj3_dataRendering
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp

server.port=2026

server.servlet.context-path=/springboot_mvc_proj3_dataRendering